### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by nakinigit** [tomasy/date-time-adapter#1]
If I go to add new rule, where do I enter the text? For example: "if DateTime minutesS is 20, turn Fan on". Date-time-adapter does not show up as an input adapter.

**Comment by tomasy** [comment]
The text "turn Fan on" is not written text. "Fan" in this example is a device that have a property "on". So "Fan" is one my devices.

**Comment by nakinigit** [comment]
Ok, I still don't understand how to use it. In your case, how did you create the rule for turning the fan on or off?

**Comment by tomasy** [comment]
I have a Zigbee device which is a switch. This device name is "Fan".
In the rules it looks like this. Perhaps this is more understandable (Sorry English is not my native langauge) But a picture tells more than 1000 words
![image](https://user-images.githubusercontent.com/21138866/47968445-7e01c300-e06a-11e8-9bd0-a4b3315d17e4.png)
or a more advance rule. Turn the fan on every second hour when it is dark outside.
![image](https://user-images.githubusercontent.com/21138866/47968487-fff1ec00-e06a-11e8-9a9e-5733f6e5247b.png)
Then you need a rule to turn the Fan off `If DateTime minutesS is 25, turn Fan off`

**Comment by nakinigit** [comment]
Ok, I see the problem. I have installed the DateTime Adapter and configured it.  I do not see it as an input device.

![image](https://user-images.githubusercontent.com/6116858/48035870-b365e980-e11a-11e8-94e3-d9429d404d17.png)

**Comment by mrinx** [comment]
I think you have to add it as a thing first; then it should become available in the rules.

**Comment by tomasy** [comment]
Strange it should be visible on the last line. Together with "Clock", "Notification" and the other 2. 
 * Is it visible in Things?
 * Could you check that is enabled in "Settings"->"Add-ons".
 * Could you also check the log file in "Settings"->"Developer"->"View Logs"->"run-app.log" if there are errors. Search for "date-time" if you can find something
 * What are your configuration data for lat, long, timezone and horizon?

**Comment by tomasy** [comment]
@nakinigit Is the problem solved?

**Comment by nakinigit** [comment]
I'm traveling, so I haven't had time to try all of your suggestions yet. It is not visible in Things. I will be returning Friday, so I will update you on the other items then.

**Comment by hwine** [comment]
I had the same issue, and @mrinx suggestion worked for me. Making *DateTime* available for use in rules was a two step process:
1. Add the **DateTime Adapter** from the ``Settings`` -> ``Addons`` display
    - go ahead and configure it
    - Valid time zone strings are the names of files or directories in ``/usr/share/zoneinfo/``
2. Add the **DateTime** Thing from the ``Things`` -> ``+`` menu

Now it will be available for use in the ``Rules`` palette.

Note that if you end up having to remove the **DateTime** Thing, a reboot appears to be needed before it will be offered again.

**Comment by tomasy** [comment]
Thanks @hwine and @mrinx I will add it to README.

About reboot I also created a bug against gateway for problem, the worklaround for me is reload of the page

**Comment by nakinigit** [comment]
I have made a little progress, but this remains exceptionally confusing to me. I finally got it to show up as a "thing", but it still is of no use:
![image](https://user-images.githubusercontent.com/6116858/48685711-8aa71080-eb6c-11e8-9ac0-4d1ec4748a31.png)

Here is my config:
![image](https://user-images.githubusercontent.com/6116858/48685773-ea052080-eb6c-11e8-898c-28ecd096a030.png)

**Comment by hwine** [comment]
@nakinigit - I ran into this - the "disconnected" state. Unfortunately I can't remember the exact workaround. 

I believe this is somewhat related to the state where a forced page load worked for @tomasy (above). I needed to do a Gateway reboot.

**Comment by tomasy** [comment]
Sorry, I thought this was solved.
Could you do a reboot of the gateway and then check the log file in `Settings` -> `Developer` -> `View Logs` -> `run-app.log`. If you find something wrong please upload it so I can check.

**Comment by nakinigit** [comment]
Looks like it is not recognizing the time zone. I have tried "PST", "UTF-8", & "Los_Angeles" (from "/usr/share/zoneinfo/")

```
2018-11-19 11:47:48.776 date-time: EXECPTION
2018-11-19 11:47:48.784 date-time: 'UTC-8'
2018-11-19 11:47:48.800 date-time: ('UTC-8',)
2018-11-19 11:47:48.824 date-time: ['Traceback (most recent call last):\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/main.py", line 51, in <module>\n    _ADAPTER = DateTimeAdapter(verbose=True)\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/pkg/date_adapter.py", line 24, in __init__\n    self.start_pairing(1)\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/pkg/date_adapter.py", line 31, in start_pairing\n    self.handle_device_added(DateTimeDevice(self, dev_id, self._config))\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/pkg/date_device.py", line 67, in __init__\n    self.dt = DT(_config.timezone, _config.lat, _config.lng, _config.horizon)\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/pkg/util.py", line 15, in __init__\n    self.next_sunrise = self.calc_sunrise()\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/pkg/util.py", line 85, in calc_sunrise\n    sunrise_local = self.to_localtime(sunrise.datetime())\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/pkg/util.py", line 112, in to_localtime\n    local_timezone = pytz.timezone(self.timezone)\n', '  File "/home/pi/.mozilla-iot/addons/date-time-adapter/lib/pytz/__init__.py", line 178, in timezone\n    raise UnknownTimeZoneError(zone)\n', "pytz.exceptions.UnknownTimeZoneError: 'UTC-8'\n"]
2018-11-19 11:47:48.834 date-time: main.py:61 INFO STOPPED DateTime Addon
2018-11-19 11:47:49.145 Plugin: date-time-adapter died, code = 0 restarting...
2018-11-19 11:47:54.045 date-time: main.py:40 INFO Starting DateTime Addon
2018-11-19 11:47:54.063 date-time: main.py:47 INFO Starting date-time-adapter. gateway_addon.API_VERSION: 2
2018-11-19 11:47:54.073 date-time: main.py:48 DEBUG Arguments list: ['/home/pi/.mozilla-iot/addons/date-time-adapter/main.py']
2018-11-19 11:47:54.081 date-time: IpcClient: Connected to server, registering...
2018-11-19 11:47:54.091 date-time: IpcClient: Received manager message: b'{"messageType":"registerPluginReply","data":{"pluginId":"date-time-adapter","ipcBaseAddr":"gateway.plugin.date-time-adapter"}}'
2018-11-19 11:47:54.096 date-time: IpcClient: Registered with PluginServer
2018-11-19 11:47:54.100 date-time: AddonManagerProxy: add_adapter: date-time-adapter
2018-11-19 11:47:54.118 date-time: config.py:19 INFO config {'lng': '-119.30', 'lat': '34.39', 'timezone': 'UTC-8', 'horizon': '-0:34'}
2018-11-19 11:47:54.122 date-time: date_adapter.py:28 INFO START Pairing
```

**Comment by tomasy** [comment]
Test with
`America/Los_Angeles`
Or look in column `TZ`at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by nakinigit** [comment]
That worked!

**Comment by tomasy** [comment]
Ok.
I have updtaed README about time zones. If it is good enough please close this.
Thanks for your help
